global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3001']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3004']

  - job_name: 'gateway'
    static_configs:
      - targets: ['api-gateway:80']
